version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/tmp
    depends_on:
      - mongo
    environment:
      DB_URL : "mongodb://admin:admin@mongo:27017/analytics_aggregator?directConnection=true&authSource=admin"

  mongo:
    image: mongo:6-jammy
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_DATABASE: analytics_aggregator
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata6:/data/db


volumes:
  dbdata6:
