services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - local-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/tmp
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/analytics_aggregator
    networks:
      - local-network

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata6:/data/db
    networks:
      - local-network


volumes:
  dbdata6:

networks:
  local-network:
    driver: bridge