# Use the official Go image
FROM golang:1.23.4

# Install Air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Set the working directory
WORKDIR /app

# Copy Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Expose the development port
EXPOSE 8080

# Command to run Air for hot-reloading
CMD ["air", "-c", ".air.toml"]